### PR TITLE
Update recurly__churn_analysis.sql

### PR DESCRIPTION
**Pull request by suelai**
Update the definition of involuntary churn, according to Recurly https://docs.recurly.com/docs/churn-analysis

**Are you a current Fivetran customer?** 
Suela Isaj, Data Engineer, Issuu

**What change(s) does this PR introduce?** 
This is a small bug in the definition of voluntary and involuntary churn

**Did you update the CHANGELOG?** 

- [ ] Yes
My change was very minimal, so I didn't update the changelog

**Does this PR introduce a breaking change?**

- [ ] Yes (please provide breaking change details below.)
- [x] No  (please provide an explanation as to how the change is non-breaking below.)
The changes only label the final output in the `recurly__churn_analysis` which is NOT incremental

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [x] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [ ] Yes, Issue/Feature [link bug/feature number here]
- [x] No 

**How did you test the PR changes?** 

 

- [ ] CircleCi  
- [x] Local (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 

- [x] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:first_quarter_moon_with_face:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

### CODE REVIEW

**Comment by fivetran-joemarkiewicz** [comment]
Hi @suelai thanks so much for opening this PR! After reviewing your update and seeing the Recurly docs do indeed include the `tax location invalid` churn reason for being involuntary, I think this is a great update to include in our package.

That being said, I wanted to confirm the reason within the data does map to this exact string. Our internal data is only test data and doesn't have the `tax location invalid` reason. Would you be able to verify that this string is exactly what you see within your warehouse?

**Comment by suelai** [comment]
@fivetran-joemarkiewicz That is a great observation, I did the change with the correct spelling (the lat commit). I initially thought it had been renamed in CTEs, but after I traced it to the source, the value should be `tax_location_invalid`

**Review by fivetran-joemarkiewicz — APPROVED** [review]
Thanks for checking the source and applying the update @suelai! This looks good to go on my end!

We are currently upgrading our package to use the latest version of dbt and dbt-utils. As such, I will fold your contribution into this branch which will shortly be merged to `main`. I also will include a small entry in the CHANGELOG to highlight your contribution.

You should see this release go live the first week of January (when we are back from our holiday break) 😄. Thank you so much for helping to contribute to the package!

**Comment by suelai** [comment]
@fivetran-joemarkiewicz You're welcome! Happy holidays 🎄

**Pull request merged**
